### PR TITLE
feat: add `options` validation (`schema-utils`)

### PR DESCRIPTION
**Pull request by michael-ciniawsky**
~Blocked by #63~

### CODE REVIEW

**Comment by mattlewis92** [comment]
Good idea! This is semver major btw as the loader will throw on invalid options now: https://github.com/webpack-contrib/schema-utils/blob/master/src/validateOptions.js#L20

**Comment by michael-ciniawsky** [comment]
You're right but luckily `v3.0.0` is in `beta` atm 😅 

> What about sourceMapUrlCallback?

It's a `{Function}` which isn't directly supported by `ajv` (JSON Schema) and I hadn't the time to look into a custom extension to support this type in `schema-utils` yet, but it is highly needed :). `additionalProperties: true` is the workaround meanwhile 😛

**Comment by mattlewis92** [comment]
Fair enough 🙂

**Comment by mattlewis92** [comment]
@michael-ciniawsky can you rebase this on master? 😄 Also might be worth adding a test that it throws on an invalid option type.

**Pull request merged**
