### PR TITLE
fix(index): merge `input` and `instrumented` sourcemaps

### LINKED ISSUE #73: Sourcemaps not tracing back to the source
The sourcemaps that `istanbul-instrumenter-loader` returns are using the input sourcemap to provide sourcemaps back to the source.

This can be reproduced in the tests for this repo.
- modify the `'sourcemap files on by default'` test in `test/index.test.js` to print the sources content:
```
  // ...
  const sourceMap = stats.compilation.assets['main.js.map'].source();
  console.log(JSON.parse(sourceMap).sourcesContent)
  // ...
```
- `npm run test`
- you should see the below printed:
```
[ '"use strict";\n\nvar _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();\n\nfunction _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }\n\nmodule.exports = function () {\n  function Foo() {\n    _classCallCheck(this, Foo);\n  }\n\n_createClass(Foo, [{\n    key: "bar",\n    value: function bar() {\n      return !!this;\n    }\n  }]);\n\n  return Foo;\n}();\n\n\n// WEBPACK FOOTER //\n// /fixtures/basic.js' ]
```
- this is how it looks formatted:
```
"use strict";

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

module.exports = function () {
    function Foo() {
      _classCallCheck(this, Foo);
  }

_createClass(Foo, [{
      key: "bar",
    value: function bar() {
        return !!this;
    }
  }]);

  return Foo;
}();


// WEBPACK FOOTER //
// /fixtures/basic.js
```
- which is quite different from the original source (`tests/fixtures/basic.js`):
```
module.exports = class Foo {
  bar() {
    return !!this;
  }
};
```

I tried tracing this around for a bit and couldn't find where it goes wrong, but it seems that the instrumenter is receiving the input sourcemap but `instrumenter.lastSourceMap()` isn't a sourcemap back to the source.

### PR DESCRIPTION
**Pull request by filipesilva**
Based on the work by @adamburgess in https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/73#issuecomment-427665948.

Added a minimal update to work with the latest webpack (used in CI tests), updated a dependency with a security issue,, fixed a test, and added a fix for the sourcemaps file names.

### Type

- [x] Bug

### Issues

- Fixes #73

### SemVer

- [x] Patch

### CODE REVIEW

**Review by michael-ciniawsky — APPROVED** [review]

**Comment by filipesilva** [comment]
Heya @michael-ciniawsky, any update on when this might be merged/released?

**Comment by L2jLiga** [comment]
@d3viant0ne, @michael-ciniawsky any updates on this?

**Comment by JamesMessinger** [comment]
I created a new npm package named [**coverage-istanbul-loader**](https://www.npmjs.com/package/coverage-istanbul-loader).  It includes [the fix mentioned above](https://github.com/webpack-contrib/istanbul-instrumenter-loader/issues/73#issuecomment-427665948) as well as other fixes and updated dependencies.

**Comment by L2jLiga** [comment]
Hey, @filipesilva,
Why to not to use `coverage-instanbul-loader`?
In my point of vision it's great way to get code coverage. Either way Angular pin all dependencies.

(just I'm happened with broken test after migration to Angular 8 and sourcemap is really broken :( )

**Pull request closed without merging**
