### PR TITLE
refactor: upgrade to webpack-defaults

### LINKED ISSUE #53: webpack-defaults upgrade
Addition of `webpack-defaults` & associated refactoring as a part of the next `Major` release

Issue exists for status tracking across the organization. 

>Please do not close

### PR DESCRIPTION
**Pull request by d3viant0ne**
**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

- Updates `loader-utils` to version `1.1.0`
- Drops `object-assign` pollyfill 
- Adds contrib standard `Babel` configuration
- Adds contrib standard `Eslint` configuration
- Refactors to utilize ES6+ JavaScript features
- Adds a `commonjs` proxy for `"main": "dist/cjs.js"` to account for ES module `.default`

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

- As a part of the `webpack-defaults` upgrade a NodeJS version of 4.3 or newer is enforced.
`"engines": { "node": ">= 4.3 < 5.0.0 || >= 5.10" }`, 

- The loader-utils package has also been updated to `^1.1.0` which also requires `NodeJS > 4.3`

**Other information**:

Merge & release as a `semver: MAJOR` with the proper `breaking change` notations in the squash commits footer.

Publish as `3.0.0` on the `beta dist-tag`

Closes #53

### CODE REVIEW

**Comment by d3viant0ne** [comment]
Note: Before this merges, I need to do a quick sanity check in a few consuming projects.

**Comment by d3viant0ne** [comment]
@bebraw - Last line in the initial pull request comment :)

**Comment by bebraw** [comment]
Ah, ok. Netcraft confirms it. 👍

**Comment by d3viant0ne** [comment]
This bricks `@angular/cli` in it's current state and will require an upgrade path and/or a pull request to the cli as a part of this going from beta to latest on the dist-tag.

Also needs to be coordinated with @TheLarkInn

**Comment by DanielaValero** [comment]
Hello @d3viant0ne 

Is there anything I can pick up here to help getting the PR finalised?

**Comment by d3viant0ne** [comment]
Not at the moment. There was a hold on the defaults upgrades while we figured out the best way to setup the Jest suites to execute tests through webpack without sacrificing Jest features

**Comment by DanielaValero** [comment]
Sure, I'll remain close, in case there is even a dot I can write to help with :)

**Comment by d3viant0ne** [comment]
@filipesilva - Friendly heads up,  there is a `semver Major` coming for `istanbul-instrumenter-loader`. No changes in functionality or the loaders API.

It applies `webpack-defaults` which in turn enforces the standard webpack versions for `engines` with the bottom limit being NodeJS 4.3. So Major for the loader, no change for `@angular/cli`.

I'll push it out on a beta dist-tag and run it through it's paces. Once we are satisfied with it, i'll ping you again incase you want to run it in dev before `3.0.0` goes to `@latest`

**Comment by filipesilva** [comment]
@d3viant0ne thanks for the heads up! I can test the new version in Angular CLI once there's a npm tag up that I can use.

**Comment by d3viant0ne** [comment]
@michael-ciniawsky - Yeah, holding off on this until we decide on the npm changes & push those out in defaults.

**Pull request merged**
